// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: common.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AccountType int32

const (
	ADMIN  AccountType = 0
	AGENCY AccountType = 1
	DIVER  AccountType = 2
)

var AccountType_name = map[int32]string{
	0: "ADMIN",
	1: "AGENCY",
	2: "DIVER",
}

var AccountType_value = map[string]int32{
	"ADMIN":  0,
	"AGENCY": 1,
	"DIVER":  2,
}

func (AccountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

type Level int32

const (
	INSTRUCTOR Level = 0
	MASTER     Level = 1
	RESCUE     Level = 2
	ADVANCED   Level = 3
	OPEN       Level = 4
)

var Level_name = map[int32]string{
	0: "INSTRUCTOR",
	1: "MASTER",
	2: "RESCUE",
	3: "ADVANCED",
	4: "OPEN",
}

var Level_value = map[string]int32{
	"INSTRUCTOR": 0,
	"MASTER":     1,
	"RESCUE":     2,
	"ADVANCED":   3,
	"OPEN":       4,
}

func (Level) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

type Address struct {
	Country      string `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Region       string `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	City         string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	AddresLine_1 string `protobuf:"bytes,4,opt,name=addres_line_1,json=addresLine1,proto3" json:"addres_line_1,omitempty"`
	AddresLine_2 string `protobuf:"bytes,5,opt,name=addres_line_2,json=addresLine2,proto3" json:"addres_line_2,omitempty"`
	PostalCode   string `protobuf:"bytes,6,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
}

func (m *Address) Reset()      { *m = Address{} }
func (*Address) ProtoMessage() {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}
func (m *Address) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Address.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return m.Size()
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Address) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetAddresLine_1() string {
	if m != nil {
		return m.AddresLine_1
	}
	return ""
}

func (m *Address) GetAddresLine_2() string {
	if m != nil {
		return m.AddresLine_2
	}
	return ""
}

func (m *Address) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func init() {
	proto.RegisterEnum("common.AccountType", AccountType_name, AccountType_value)
	proto.RegisterEnum("common.Level", Level_name, Level_value)
	proto.RegisterType((*Address)(nil), "common.Address")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xb1, 0x6a, 0xfa, 0x40,
	0x1c, 0xc7, 0x73, 0x1a, 0xa3, 0xfe, 0xf4, 0xff, 0x27, 0xdc, 0x50, 0x32, 0x5d, 0x8b, 0x53, 0x71,
	0x50, 0xb4, 0x5b, 0xb7, 0x6b, 0x72, 0x88, 0xa0, 0xb1, 0xc4, 0x28, 0xb4, 0x8b, 0x68, 0x72, 0x94,
	0x80, 0xe6, 0x42, 0x4c, 0x0b, 0x6e, 0x7d, 0x84, 0x3e, 0x46, 0x1f, 0xa1, 0x8f, 0xd0, 0xd1, 0xd1,
	0xb1, 0x9e, 0x4b, 0x47, 0x1f, 0xa1, 0x78, 0x69, 0x17, 0xb7, 0xef, 0xf7, 0xf3, 0xfd, 0x70, 0x1c,
	0x3f, 0xa8, 0x07, 0x62, 0xb5, 0x12, 0x71, 0x2b, 0x49, 0x45, 0x26, 0xb0, 0x91, 0xb7, 0xc6, 0x07,
	0x82, 0x32, 0x0d, 0xc3, 0x94, 0xaf, 0xd7, 0xd8, 0x82, 0x72, 0x20, 0x9e, 0xe3, 0x2c, 0xdd, 0x58,
	0xe8, 0x0a, 0x5d, 0x57, 0xbd, 0xbf, 0x8a, 0x2f, 0xc0, 0x48, 0xf9, 0x53, 0x24, 0x62, 0xab, 0xa0,
	0x86, 0xdf, 0x86, 0x31, 0xe8, 0x41, 0x94, 0x6d, 0xac, 0xa2, 0xa2, 0x2a, 0xe3, 0x06, 0xfc, 0x9b,
	0xab, 0x07, 0x67, 0xcb, 0x28, 0xe6, 0xb3, 0x8e, 0xa5, 0xab, 0xb1, 0x96, 0xc3, 0x41, 0x14, 0xf3,
	0xce, 0xb9, 0xd3, 0xb5, 0x4a, 0xe7, 0x4e, 0x17, 0x5f, 0x42, 0x2d, 0x11, 0xeb, 0x6c, 0xbe, 0x9c,
	0x05, 0x22, 0xe4, 0x96, 0xa1, 0x0c, 0xc8, 0x91, 0x2d, 0x42, 0xde, 0x6c, 0x43, 0x8d, 0x06, 0xea,
	0x87, 0xfe, 0x26, 0xe1, 0xb8, 0x0a, 0x25, 0xea, 0x0c, 0xfb, 0xae, 0xa9, 0x61, 0x00, 0x83, 0xf6,
	0x98, 0x6b, 0x3f, 0x98, 0xe8, 0x84, 0x9d, 0xfe, 0x94, 0x79, 0x66, 0xa1, 0xd9, 0x83, 0xd2, 0x80,
	0xbf, 0xf0, 0x25, 0xfe, 0x0f, 0xd0, 0x77, 0xc7, 0xbe, 0x37, 0xb1, 0xfd, 0x91, 0x97, 0xfb, 0x43,
	0x3a, 0xf6, 0x99, 0x67, 0xa2, 0x53, 0xf6, 0xd8, 0xd8, 0x9e, 0x30, 0xb3, 0x80, 0xeb, 0x50, 0xa1,
	0xce, 0x94, 0xba, 0x36, 0x73, 0xcc, 0x22, 0xae, 0x80, 0x3e, 0xba, 0x67, 0xae, 0xa9, 0xdf, 0xdd,
	0x6e, 0xf7, 0x44, 0xdb, 0xed, 0x89, 0x76, 0xdc, 0x13, 0xf4, 0x2a, 0x09, 0x7a, 0x97, 0x04, 0x7d,
	0x4a, 0x82, 0xb6, 0x92, 0xa0, 0x2f, 0x49, 0xd0, 0xb7, 0x24, 0xda, 0x51, 0x12, 0xf4, 0x76, 0x20,
	0xda, 0xf6, 0x40, 0xb4, 0xdd, 0x81, 0x68, 0x8f, 0x7a, 0xab, 0x9d, 0x2c, 0x16, 0x86, 0xba, 0xff,
	0xcd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x17, 0x81, 0xfc, 0x43, 0x8f, 0x01, 0x00, 0x00,
}

func (x AccountType) String() string {
	s, ok := AccountType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x Level) String() string {
	s, ok := Level_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *Address) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Address)
	if !ok {
		that2, ok := that.(Address)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Country != that1.Country {
		return false
	}
	if this.Region != that1.Region {
		return false
	}
	if this.City != that1.City {
		return false
	}
	if this.AddresLine_1 != that1.AddresLine_1 {
		return false
	}
	if this.AddresLine_2 != that1.AddresLine_2 {
		return false
	}
	if this.PostalCode != that1.PostalCode {
		return false
	}
	return true
}
func (this *Address) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 10)
	s = append(s, "&pb.Address{")
	s = append(s, "Country: "+fmt.Sprintf("%#v", this.Country)+",\n")
	s = append(s, "Region: "+fmt.Sprintf("%#v", this.Region)+",\n")
	s = append(s, "City: "+fmt.Sprintf("%#v", this.City)+",\n")
	s = append(s, "AddresLine_1: "+fmt.Sprintf("%#v", this.AddresLine_1)+",\n")
	s = append(s, "AddresLine_2: "+fmt.Sprintf("%#v", this.AddresLine_2)+",\n")
	s = append(s, "PostalCode: "+fmt.Sprintf("%#v", this.PostalCode)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringCommon(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Address) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Address) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Address) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PostalCode) > 0 {
		i -= len(m.PostalCode)
		copy(dAtA[i:], m.PostalCode)
		i = encodeVarintCommon(dAtA, i, uint64(len(m.PostalCode)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.AddresLine_2) > 0 {
		i -= len(m.AddresLine_2)
		copy(dAtA[i:], m.AddresLine_2)
		i = encodeVarintCommon(dAtA, i, uint64(len(m.AddresLine_2)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.AddresLine_1) > 0 {
		i -= len(m.AddresLine_1)
		copy(dAtA[i:], m.AddresLine_1)
		i = encodeVarintCommon(dAtA, i, uint64(len(m.AddresLine_1)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.City) > 0 {
		i -= len(m.City)
		copy(dAtA[i:], m.City)
		i = encodeVarintCommon(dAtA, i, uint64(len(m.City)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Region) > 0 {
		i -= len(m.Region)
		copy(dAtA[i:], m.Region)
		i = encodeVarintCommon(dAtA, i, uint64(len(m.Region)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Country) > 0 {
		i -= len(m.Country)
		copy(dAtA[i:], m.Country)
		i = encodeVarintCommon(dAtA, i, uint64(len(m.Country)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCommon(dAtA []byte, offset int, v uint64) int {
	offset -= sovCommon(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Address) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Country)
	if l > 0 {
		n += 1 + l + sovCommon(uint64(l))
	}
	l = len(m.Region)
	if l > 0 {
		n += 1 + l + sovCommon(uint64(l))
	}
	l = len(m.City)
	if l > 0 {
		n += 1 + l + sovCommon(uint64(l))
	}
	l = len(m.AddresLine_1)
	if l > 0 {
		n += 1 + l + sovCommon(uint64(l))
	}
	l = len(m.AddresLine_2)
	if l > 0 {
		n += 1 + l + sovCommon(uint64(l))
	}
	l = len(m.PostalCode)
	if l > 0 {
		n += 1 + l + sovCommon(uint64(l))
	}
	return n
}

func sovCommon(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCommon(x uint64) (n int) {
	return sovCommon(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Address) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Address{`,
		`Country:` + fmt.Sprintf("%v", this.Country) + `,`,
		`Region:` + fmt.Sprintf("%v", this.Region) + `,`,
		`City:` + fmt.Sprintf("%v", this.City) + `,`,
		`AddresLine_1:` + fmt.Sprintf("%v", this.AddresLine_1) + `,`,
		`AddresLine_2:` + fmt.Sprintf("%v", this.AddresLine_2) + `,`,
		`PostalCode:` + fmt.Sprintf("%v", this.PostalCode) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringCommon(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Address) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCommon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Address: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Address: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Country", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Country = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Region", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Region = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field City", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.City = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddresLine_1", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddresLine_1 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddresLine_2", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddresLine_2 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostalCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PostalCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCommon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCommon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCommon(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCommon
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCommon
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCommon
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCommon
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCommon        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCommon          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCommon = fmt.Errorf("proto: unexpected end of group")
)
