// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: diver.proto

package pb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DiverRequest struct {
	FirstName   string     `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName    string     `protobuf:"bytes,20,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber string     `protobuf:"bytes,30,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Documents   []*File    `protobuf:"bytes,40,rep,name=documents,proto3" json:"documents,omitempty"`
	BirthDate   *time.Time `protobuf:"bytes,50,opt,name=birth_date,json=birthDate,proto3,stdtime" json:"birth_date,omitempty"`
	Level       LevelType  `protobuf:"varint,60,opt,name=level,proto3,enum=model.LevelType" json:"level,omitempty"`
}

func (m *DiverRequest) Reset()      { *m = DiverRequest{} }
func (*DiverRequest) ProtoMessage() {}
func (*DiverRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_765ae613bf716c8b, []int{0}
}
func (m *DiverRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DiverRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DiverRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DiverRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiverRequest.Merge(m, src)
}
func (m *DiverRequest) XXX_Size() int {
	return m.Size()
}
func (m *DiverRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiverRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiverRequest proto.InternalMessageInfo

func (m *DiverRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *DiverRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *DiverRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *DiverRequest) GetDocuments() []*File {
	if m != nil {
		return m.Documents
	}
	return nil
}

func (m *DiverRequest) GetBirthDate() *time.Time {
	if m != nil {
		return m.BirthDate
	}
	return nil
}

func (m *DiverRequest) GetLevel() LevelType {
	if m != nil {
		return m.Level
	}
	return INSTRUCTOR
}

func init() {
	proto.RegisterType((*DiverRequest)(nil), "diver.DiverRequest")
}

func init() { proto.RegisterFile("diver.proto", fileDescriptor_765ae613bf716c8b) }

var fileDescriptor_765ae613bf716c8b = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0x31, 0x4b, 0xfb, 0x40,
	0x18, 0xc6, 0x73, 0xff, 0x7f, 0x2b, 0xe6, 0x52, 0x44, 0x82, 0x43, 0xa8, 0xf8, 0x36, 0x3a, 0x48,
	0x1c, 0x4c, 0x21, 0x6e, 0x22, 0x08, 0xa5, 0x38, 0x49, 0x87, 0xd0, 0xc9, 0xa5, 0x24, 0xcd, 0xdb,
	0x34, 0x90, 0xcb, 0xc5, 0xe4, 0x52, 0x70, 0xd3, 0x6f, 0xd0, 0x8f, 0xe1, 0x47, 0x71, 0xec, 0xd8,
	0x4d, 0x7b, 0x5d, 0x1c, 0xfb, 0x11, 0xa4, 0x97, 0x96, 0x6e, 0x79, 0x7e, 0xbf, 0x27, 0xbc, 0xf7,
	0x50, 0x23, 0x4a, 0x66, 0x58, 0xb8, 0x79, 0xc1, 0x05, 0x37, 0x9b, 0x2a, 0xb4, 0x0d, 0xc6, 0x23,
	0x4c, 0x6b, 0xd6, 0xbe, 0x8d, 0x13, 0x31, 0xad, 0x42, 0x77, 0xcc, 0x59, 0x37, 0xe6, 0x31, 0xef,
	0x2a, 0x1c, 0x56, 0x13, 0x95, 0x54, 0x50, 0x5f, 0xbb, 0x7a, 0x27, 0xe6, 0x3c, 0x4e, 0xf1, 0xd0,
	0x12, 0x09, 0xc3, 0x52, 0x04, 0x2c, 0xaf, 0x0b, 0x57, 0x1f, 0xff, 0x68, 0xab, 0xbf, 0x3d, 0xe3,
	0xe3, 0x6b, 0x85, 0xa5, 0x30, 0x2f, 0x28, 0x9d, 0x24, 0x45, 0x29, 0x46, 0x59, 0xc0, 0xd0, 0x22,
	0x36, 0x71, 0x74, 0x5f, 0x57, 0x64, 0x10, 0x30, 0x34, 0xcf, 0xa9, 0x9e, 0x06, 0x7b, 0x7b, 0xa6,
	0xec, 0xf1, 0x16, 0x28, 0x79, 0x49, 0x5b, 0xf9, 0x94, 0x67, 0x38, 0xca, 0x2a, 0x16, 0x62, 0x61,
	0x81, 0xf2, 0x86, 0x62, 0x03, 0x85, 0xcc, 0x1b, 0xaa, 0x47, 0x7c, 0x5c, 0x31, 0xcc, 0x44, 0x69,
	0x39, 0xf6, 0x7f, 0xc7, 0xf0, 0x0c, 0xb7, 0x1e, 0xf8, 0x94, 0xa4, 0xe8, 0x1f, 0xac, 0xf9, 0x48,
	0x69, 0x98, 0x14, 0x62, 0x3a, 0x8a, 0x02, 0x81, 0x96, 0x67, 0x13, 0xc7, 0xf0, 0xda, 0x6e, 0x3d,
	0xc8, 0xdd, 0x0f, 0x72, 0x87, 0xfb, 0x41, 0xbd, 0xc6, 0xfc, 0xbb, 0x43, 0x7c, 0x5d, 0xfd, 0xd3,
	0x0f, 0x04, 0x9a, 0xd7, 0xb4, 0x99, 0xe2, 0x0c, 0x53, 0xeb, 0xc1, 0x26, 0xce, 0x89, 0x77, 0xba,
	0xbb, 0xf3, 0xbc, 0x65, 0xc3, 0xb7, 0x1c, 0xfd, 0x5a, 0xf7, 0xee, 0x17, 0x2b, 0xd0, 0x96, 0x2b,
	0xd0, 0x36, 0x2b, 0x20, 0xef, 0x12, 0xc8, 0xa7, 0x04, 0xf2, 0x25, 0x81, 0x2c, 0x24, 0x90, 0x1f,
	0x09, 0xe4, 0x57, 0x82, 0xb6, 0x91, 0x40, 0xe6, 0x6b, 0xd0, 0x16, 0x6b, 0xd0, 0x96, 0x6b, 0xd0,
	0x5e, 0x1a, 0x6e, 0x37, 0x0f, 0xc3, 0x23, 0xf5, 0x90, 0xbb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xcd, 0x61, 0x95, 0x22, 0xb9, 0x01, 0x00, 0x00,
}

func (this *DiverRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DiverRequest)
	if !ok {
		that2, ok := that.(DiverRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.FirstName != that1.FirstName {
		return false
	}
	if this.LastName != that1.LastName {
		return false
	}
	if this.PhoneNumber != that1.PhoneNumber {
		return false
	}
	if len(this.Documents) != len(that1.Documents) {
		return false
	}
	for i := range this.Documents {
		if !this.Documents[i].Equal(that1.Documents[i]) {
			return false
		}
	}
	if that1.BirthDate == nil {
		if this.BirthDate != nil {
			return false
		}
	} else if !this.BirthDate.Equal(*that1.BirthDate) {
		return false
	}
	if this.Level != that1.Level {
		return false
	}
	return true
}
func (this *DiverRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 10)
	s = append(s, "&pb.DiverRequest{")
	s = append(s, "FirstName: "+fmt.Sprintf("%#v", this.FirstName)+",\n")
	s = append(s, "LastName: "+fmt.Sprintf("%#v", this.LastName)+",\n")
	s = append(s, "PhoneNumber: "+fmt.Sprintf("%#v", this.PhoneNumber)+",\n")
	if this.Documents != nil {
		s = append(s, "Documents: "+fmt.Sprintf("%#v", this.Documents)+",\n")
	}
	s = append(s, "BirthDate: "+fmt.Sprintf("%#v", this.BirthDate)+",\n")
	s = append(s, "Level: "+fmt.Sprintf("%#v", this.Level)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringDiver(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *DiverRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DiverRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DiverRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Level != 0 {
		i = encodeVarintDiver(dAtA, i, uint64(m.Level))
		i--
		dAtA[i] = 0x3
		i--
		dAtA[i] = 0xe0
	}
	if m.BirthDate != nil {
		n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.BirthDate, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.BirthDate):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintDiver(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x3
		i--
		dAtA[i] = 0x92
	}
	if len(m.Documents) > 0 {
		for iNdEx := len(m.Documents) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Documents[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDiver(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2
			i--
			dAtA[i] = 0xc2
		}
	}
	if len(m.PhoneNumber) > 0 {
		i -= len(m.PhoneNumber)
		copy(dAtA[i:], m.PhoneNumber)
		i = encodeVarintDiver(dAtA, i, uint64(len(m.PhoneNumber)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xf2
	}
	if len(m.LastName) > 0 {
		i -= len(m.LastName)
		copy(dAtA[i:], m.LastName)
		i = encodeVarintDiver(dAtA, i, uint64(len(m.LastName)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa2
	}
	if len(m.FirstName) > 0 {
		i -= len(m.FirstName)
		copy(dAtA[i:], m.FirstName)
		i = encodeVarintDiver(dAtA, i, uint64(len(m.FirstName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDiver(dAtA []byte, offset int, v uint64) int {
	offset -= sovDiver(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DiverRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FirstName)
	if l > 0 {
		n += 1 + l + sovDiver(uint64(l))
	}
	l = len(m.LastName)
	if l > 0 {
		n += 2 + l + sovDiver(uint64(l))
	}
	l = len(m.PhoneNumber)
	if l > 0 {
		n += 2 + l + sovDiver(uint64(l))
	}
	if len(m.Documents) > 0 {
		for _, e := range m.Documents {
			l = e.Size()
			n += 2 + l + sovDiver(uint64(l))
		}
	}
	if m.BirthDate != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.BirthDate)
		n += 2 + l + sovDiver(uint64(l))
	}
	if m.Level != 0 {
		n += 2 + sovDiver(uint64(m.Level))
	}
	return n
}

func sovDiver(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDiver(x uint64) (n int) {
	return sovDiver(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *DiverRequest) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForDocuments := "[]*File{"
	for _, f := range this.Documents {
		repeatedStringForDocuments += strings.Replace(fmt.Sprintf("%v", f), "File", "File", 1) + ","
	}
	repeatedStringForDocuments += "}"
	s := strings.Join([]string{`&DiverRequest{`,
		`FirstName:` + fmt.Sprintf("%v", this.FirstName) + `,`,
		`LastName:` + fmt.Sprintf("%v", this.LastName) + `,`,
		`PhoneNumber:` + fmt.Sprintf("%v", this.PhoneNumber) + `,`,
		`Documents:` + repeatedStringForDocuments + `,`,
		`BirthDate:` + strings.Replace(fmt.Sprintf("%v", this.BirthDate), "Timestamp", "timestamp.Timestamp", 1) + `,`,
		`Level:` + fmt.Sprintf("%v", this.Level) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringDiver(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *DiverRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDiver
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DiverRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DiverRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDiver
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDiver
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FirstName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDiver
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDiver
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 30:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PhoneNumber", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDiver
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDiver
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PhoneNumber = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 40:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Documents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDiver
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDiver
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Documents = append(m.Documents, &File{})
			if err := m.Documents[len(m.Documents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 50:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BirthDate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDiver
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDiver
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BirthDate == nil {
				m.BirthDate = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.BirthDate, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 60:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Level", wireType)
			}
			m.Level = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Level |= LevelType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDiver(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDiver
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDiver(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDiver
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDiver
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDiver
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDiver
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDiver
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDiver
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDiver        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDiver          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDiver = fmt.Errorf("proto: unexpected end of group")
)
